import 'package:flutter/material.dart';
import 'package:lotus_forms_package/lotus_forms_package.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 30),
          child: DynamicForms(
            formId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
            jwtToken:
                'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJiM2EyN2FhNC00ZmRmLTRmMjMtYTFiZC1kNTgwZTdmM2M4NGYiLCJzdWIiOiJsb3R1cy10ZXN0K3p6QGlubm93aXNlLmNvbSIsImp0aSI6IjMwNmZlMDhmLWVjOGQtNGQ4ZC04YTNjLTY3YjhkM2ZhZmMyYSIsImdpdmVuX25hbWUiOiJaZW5kZWEiLCJmYW1pbHlfbmFtZSI6Ilp1cmlnIiwiaXNGaWVsZFdvcmtlciI6IlRydWUiLCJ2ZW5kb3JJZCI6IjQ2YjM1NGU2LTNjNzYtNDVjOC1hZjBmLWU2NzdmODkwYjdhYyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbSBGV3MiLCJwZXJtaXNzaW9ucyI6WyJEYXNoYm9hcmQuSW5jb21wbGV0ZUFkZHJlc3MiLCJEYXNoYm9hcmQuQ2FzZXNOb0F0dGVtcHRzIiwiQ2FzZS5SZWFkVmlkZW8iLCJEYXNoYm9hcmQuRGVsYXllZERhdGFFbnRyeSIsIkNhc2UuV3JpdGVDYXNlc05vdGVzIiwiQXZhaWxhYmlsaXR5LlZpZXdEZXRhaWxzIiwiQ2FzZS5SZWFkQ2FzZXNOb3RlcyIsIkF0dGVtcHQuVmlld1JlbWluZGVycyIsIlVzZXIuRWRpdCIsIkF2YWlsYWJpbGl0eS5MaXN0IiwiVXNlci5MaXN0IiwiSW5zdXJhbmNlLkxpc3QiLCJTZXJ2aWNlLkxpc3QiLCJNZW1iZXIuTWFpbkluZm9ybWF0aW9uIiwiQ2FzZS5SZWFkTm90ZXMiLCJDYXNlLkxpc3QiLCJDYXNlLkVkaXREb2N1bWVudCIsIk1lbWJlci5WaWV3UGVyc29uYWxEZXRhaWxzIiwiQ2FzZS5Xcml0ZVZpZGVvIiwiQ2FzZS5SZWZ1c2VTZXJ2aWNlIiwiTWVtYmVyLldyaXRlTm90ZXMiLCJNZW1iZXIuU2VydmljZXMiLCJNZW1iZXIuUmVhZE1lZGljYWlkSWQiLCJDYWxlbmRhci5TZWVDYWxlbmRhciIsIkNhc2UuQ2hhdCIsIkF0dGVtcHQuTGlzdCIsIlJlcG9ydC5MaXN0IiwiTWVtYmVyLkVkaXRQZXJzb25hbERldGFpbHMiLCJDYXNlLkFkZFNlcnZpY2UiLCJNZW1iZXIuVmlld0RldGFpbHMiLCJDYXNlLkRvY3VtZW50c0xpc3QiLCJDYXNlLk1haW5JbmZvcm1hdGlvbiIsIkRhc2hib2FyZC5TY2hlZHVsZWRBcHBvaW50bWVudCIsIkNhbGVuZGFyLkNyZWF0ZUF2YWlsYWJpbGl0eSIsIk1lbWJlci5WaWV3TG9ncyIsIkNhc2UuVmlld0RldGFpbHMiLCJDYXNlLlNlZURvY3VtZW50cyIsIkNhc2UuU2VlU2VydmljZXMiLCJBdHRlbXB0LkNyZWF0ZSIsIk1lbWJlci5IaXN0b3J5IiwiQ2FzZS5FZGl0IiwiTWVtYmVyLlZpZXdDYXJkRGV0YWlscyIsIkNhc2UuUmVhZE1lZGljYWlkSWQiLCJVc2VyLkNyZWF0ZSIsIkNhc2UuU2VlQ2hhdCIsIkRhc2hib2FyZC5Bc3NpZ25lZENhc2VzIiwiTWVtYmVyLkxpc3QiXSwibmJmIjoxNzY1Nzk0NTQ2LCJleHAiOjE3NjU3OTU0NDYsImlzcyI6IllvdXJUZXN0SXNzdWVyIiwiYXVkIjoiWW91clRlc3RBdWRpZW5jZSJ9.7P77JUPAFgGNMJRVyGazVwP5TEh8iEaRt8Z3HdMzhsg',
          ),
        ),
      ),
    );
  }
}
