// Mocks generated by Mockito 5.4.4 from annotations
// in lotus_forms_package/test/helpers/main_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart'
    as _i6;
import 'package:lotus_forms_package/src/core/network/network_info.dart' as _i5;
import 'package:lotus_forms_package/src/data/data.dart' as _i2;
import 'package:lotus_forms_package/src/domain/domain.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFormEntity_0 extends _i1.SmartFake implements _i2.FormEntity {
  _FakeFormEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFormModel_1 extends _i1.SmartFake implements _i3.FormModel {
  _FakeFormModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FormProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormProvider extends _i1.Mock implements _i2.FormProvider {
  MockFormProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.FormEntity>> getForms() => (super.noSuchMethod(
        Invocation.method(
          #getForms,
          [],
        ),
        returnValue: _i4.Future<List<_i2.FormEntity>>.value(<_i2.FormEntity>[]),
      ) as _i4.Future<List<_i2.FormEntity>>);

  @override
  _i4.Future<_i2.FormEntity> getForm(String? formId) => (super.noSuchMethod(
        Invocation.method(
          #getForm,
          [formId],
        ),
        returnValue: _i4.Future<_i2.FormEntity>.value(_FakeFormEntity_0(
          this,
          Invocation.method(
            #getForm,
            [formId],
          ),
        )),
      ) as _i4.Future<_i2.FormEntity>);

  @override
  _i4.Future<void> saveForm(_i2.FormEntity? form) => (super.noSuchMethod(
        Invocation.method(
          #saveForm,
          [form],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i2.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> hasForms() => (super.noSuchMethod(
        Invocation.method(
          #hasForms,
          [],
        ),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Future<List<_i2.FormEntity>> getForms() => (super.noSuchMethod(
        Invocation.method(
          #getForms,
          [],
        ),
        returnValue: _i4.Future<List<_i2.FormEntity>>.value(<_i2.FormEntity>[]),
      ) as _i4.Future<List<_i2.FormEntity>>);

  @override
  _i4.Future<void> insertForm(_i2.FormEntity? form) => (super.noSuchMethod(
        Invocation.method(
          #insertForm,
          [form],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteForm(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteForm,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FormRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormRepository extends _i1.Mock implements _i3.FormRepository {
  MockFormRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i3.FormModel>> getForms() => (super.noSuchMethod(
        Invocation.method(
          #getForms,
          [],
        ),
        returnValue: _i4.Future<List<_i3.FormModel>>.value(<_i3.FormModel>[]),
      ) as _i4.Future<List<_i3.FormModel>>);

  @override
  _i4.Future<_i3.FormModel> getForm(String? formId) => (super.noSuchMethod(
        Invocation.method(
          #getForm,
          [formId],
        ),
        returnValue: _i4.Future<_i3.FormModel>.value(_FakeFormModel_1(
          this,
          Invocation.method(
            #getForm,
            [formId],
          ),
        )),
      ) as _i4.Future<_i3.FormModel>);

  @override
  _i4.Future<void> saveForm(_i3.FormModel? form) => (super.noSuchMethod(
        Invocation.method(
          #saveForm,
          [form],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [OfflineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineRepository extends _i1.Mock implements _i3.OfflineRepository {
  MockOfflineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> hasForms() => (super.noSuchMethod(
        Invocation.method(
          #hasForms,
          [],
        ),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Future<List<_i3.FormModel>> getForms() => (super.noSuchMethod(
        Invocation.method(
          #getForms,
          [],
        ),
        returnValue: _i4.Future<List<_i3.FormModel>>.value(<_i3.FormModel>[]),
      ) as _i4.Future<List<_i3.FormModel>>);

  @override
  _i4.Future<void> deleteForm(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteForm,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SynchronizeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSynchronizeUseCase extends _i1.Mock
    implements _i3.SynchronizeUseCase {
  MockSynchronizeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> watchPendingStatus() => (super.noSuchMethod(
        Invocation.method(
          #watchPendingStatus,
          [],
        ),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Future<void> executeSync() => (super.noSuchMethod(
        Invocation.method(
          #executeSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<_i6.InternetStatus> get onStatusChange => (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i4.Stream<_i6.InternetStatus>.empty(),
      ) as _i4.Stream<_i6.InternetStatus>);
}
